---
- name: Install Datadog package
  apt:
    deb: /tmp/datadog_package.deb

- name: Run the equivalent of "apt-get clean" as a separate step
  apt:
    clean: yes

#Instead of downloading and installing from tmp location, we can directly install from remote https
#- name: Install a .deb package from the internet
#  ansible.builtin.apt:
#    deb: https://example.com/python-ppq_0.1-1_all.deb